version: '3'
services:
  gekko:
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./:/usr/src/app/
    entrypoint: ['sh', 'docker-entrypoint.sh']
    command: ["--config", "config.js", "--ui"]
    user: 1000:1000
    links:
      - redis
      - postgresql
    environment:
     - HOST
     - PORT
     - USE_SSL
    ports: # you can comment this out when using the nginx frontend
      - "${PORT}:${PORT}"
## optionally set nginx vars if you wish to frontend it with nginx
#    environment:
#     - VIRTUAL_HOST=gekko
#     - PORT=3000
#     - DOMAIN=gekko

  redis:
    image: redis:latest
    volumes:
      - ./volumes/redis:/data

#  nginx:
#    restart: always
#    image: jwilder/nginx-proxy
#    ports:
#     - "80:80"
#    volumes:
#     - /var/run/docker.sock:/tmp/docker.sock:ro

  postgresql:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./_postgresql:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: gekko
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
