version: '3'

services:
  gekko:
    container_name: gekko_gekko
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
      - ./:/usr/src/app/
    entrypoint: ['sh', 'docker-entrypoint.sh']
    command: ["--config", "config.js", "--ui"]
    user: 1000:1000
    links:
      - redis
      - postgresql
    environment:
     - HOST=localhost
     - PORT=3000
     - USE_SSL=0
    ports:
      - "${PORT}:${PORT}"
      - "3001:3001"

  redis:
    container_name: gekko_redis
    image: redis:latest
    volumes:
      - ./volumes/redis:/data

  postgresql:
    container_name: gekko_postgresql
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresqldb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: gekko
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  adminer:
    container_name: gekko_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresqldb:
    driver: local
